package com.g4.view;

import com.g4.model.entity.MyDoublyLinkedList;
import com.g4.model.repository.UserDAO;
import javax.swing.table.DefaultTableModel;

public class frmClients extends javax.swing.JFrame {

    public int mouseX, mouseY;
    private UserDAO userC = new UserDAO();
  
    public frmClients() {
        initComponents();
        upload();
    }     

    public void upload() {
        userC.read();
        DefaultTableModel model = (DefaultTableModel) tblClients.getModel();
             
        for (Object[] object : MyDoublyLinkedList.upload()) {
            model.addRow(object);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblAdmin = new javax.swing.JLabel();
        txtAdmin = new javax.swing.JLabel();
        btnReturn = new javax.swing.JLabel();
        titlePanel = new javax.swing.JPanel();
        exitPanel = new javax.swing.JPanel();
        btnExit = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        scrollClients = new javax.swing.JScrollPane();
        tblClients = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Roboto Medium", 0, 36)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(0, 0, 0));
        lblTitle.setText("Pasajeros Registrados");
        jPanel1.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, -1, -1));

        lblAdmin.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        lblAdmin.setForeground(new java.awt.Color(0, 0, 0));
        lblAdmin.setText("Administrador:");
        jPanel1.add(lblAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 130, -1));

        txtAdmin.setBackground(new java.awt.Color(204, 255, 204));
        txtAdmin.setFont(new java.awt.Font("Roboto Light", 3, 18)); // NOI18N
        txtAdmin.setForeground(new java.awt.Color(0, 0, 0));
        txtAdmin.setText("Admin");
        txtAdmin.setToolTipText("");
        txtAdmin.setRequestFocusEnabled(false);
        jPanel1.add(txtAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 420, -1));

        btnReturn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/g4/view/images/return.png"))); // NOI18N
        btnReturn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnReturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 530, -1, 30));

        titlePanel.setBackground(new java.awt.Color(0, 22, 59));

        exitPanel.setBackground(new java.awt.Color(0, 22, 59));

        btnExit.setBackground(new java.awt.Color(0, 22, 59));
        btnExit.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnExit.setText("X");
        btnExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout exitPanelLayout = new javax.swing.GroupLayout(exitPanel);
        exitPanel.setLayout(exitPanelLayout);
        exitPanelLayout.setHorizontalGroup(
            exitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, exitPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        exitPanelLayout.setVerticalGroup(
            exitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, exitPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout titlePanelLayout = new javax.swing.GroupLayout(titlePanel);
        titlePanel.setLayout(titlePanelLayout);
        titlePanelLayout.setHorizontalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, titlePanelLayout.createSequentialGroup()
                .addGap(0, 870, Short.MAX_VALUE)
                .addComponent(exitPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        titlePanelLayout.setVerticalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, titlePanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(exitPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(titlePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, -1));

        jLabel1.setText("Ordenar por:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 160, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Nombre", "Precio de boleto", "Fecha de ida" }));
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 190, 100, -1));

        scrollClients.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        scrollClients.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        scrollClients.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        scrollClients.setFocusTraversalPolicyProvider(true);
        scrollClients.setRequestFocusEnabled(false);
        scrollClients.setViewportView(null);

        tblClients.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "DNI", "Telefono", "Email", "Origen", "Destino", "Fecha de Ida", "Precio de boleto"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblClients.setRowHeight(30);
        tblClients.getTableHeader().setReorderingAllowed(false);
        scrollClients.setViewportView(tblClients);
        if (tblClients.getColumnModel().getColumnCount() > 0) {
            tblClients.getColumnModel().getColumn(0).setResizable(false);
            tblClients.getColumnModel().getColumn(0).setPreferredWidth(30);
            tblClients.getColumnModel().getColumn(1).setResizable(false);
            tblClients.getColumnModel().getColumn(2).setResizable(false);
            tblClients.getColumnModel().getColumn(2).setPreferredWidth(60);
            tblClients.getColumnModel().getColumn(3).setResizable(false);
            tblClients.getColumnModel().getColumn(3).setPreferredWidth(70);
            tblClients.getColumnModel().getColumn(4).setResizable(false);
            tblClients.getColumnModel().getColumn(5).setResizable(false);
            tblClients.getColumnModel().getColumn(6).setResizable(false);
            tblClients.getColumnModel().getColumn(7).setResizable(false);
            tblClients.getColumnModel().getColumn(8).setResizable(false);
        }

        jPanel1.add(scrollClients, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 710, 300));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel btnExit;
    public javax.swing.JLabel btnReturn;
    public javax.swing.JPanel exitPanel;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAdmin;
    private javax.swing.JLabel lblTitle;
    public javax.swing.JScrollPane scrollClients;
    public javax.swing.JTable tblClients;
    public javax.swing.JPanel titlePanel;
    public javax.swing.JLabel txtAdmin;
    // End of variables declaration//GEN-END:variables
}