package com.g4.view;

import java.awt.Color;

/**
 *
 * @author jccr_
 */
public class frmDestination extends javax.swing.JFrame {

    public int xMouse, yMouse;
    public frmDestination() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo = new javax.swing.JLabel();
        Barra_superior = new javax.swing.JPanel();
        Boton_cerrar = new javax.swing.JPanel();
        X_salir = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Titulo1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        Titulo_nombre1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        Titulo_nombre2 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        Titulo_nombre3 = new javax.swing.JLabel();
        Box_destinos = new javax.swing.JComboBox<>();
        Boton = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Boton1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        Barra_superior1 = new javax.swing.JPanel();
        Boton_cerrar1 = new javax.swing.JPanel();
        X_salir1 = new javax.swing.JLabel();

        Titulo.setBackground(new java.awt.Color(0, 0, 0));
        Titulo.setFont(new java.awt.Font("Roboto Medium", 0, 36)); // NOI18N
        Titulo.setForeground(new java.awt.Color(0, 0, 0));
        Titulo.setText("REGISTRO");

        Barra_superior.setBackground(new java.awt.Color(0, 22, 59));
        Barra_superior.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                Barra_superiorMouseDragged(evt);
            }
        });
        Barra_superior.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Barra_superiorMousePressed(evt);
            }
        });

        Boton_cerrar.setBackground(new java.awt.Color(63, 31, 46));

        X_salir.setBackground(new java.awt.Color(255, 255, 255));
        X_salir.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        X_salir.setForeground(new java.awt.Color(255, 255, 255));
        X_salir.setText("  X");
        X_salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        X_salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                X_salirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                X_salirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                X_salirMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                X_salirMousePressed(evt);
            }
        });

        javax.swing.GroupLayout Boton_cerrarLayout = new javax.swing.GroupLayout(Boton_cerrar);
        Boton_cerrar.setLayout(Boton_cerrarLayout);
        Boton_cerrarLayout.setHorizontalGroup(
            Boton_cerrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(X_salir, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
        );
        Boton_cerrarLayout.setVerticalGroup(
            Boton_cerrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(X_salir, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout Barra_superiorLayout = new javax.swing.GroupLayout(Barra_superior);
        Barra_superior.setLayout(Barra_superiorLayout);
        Barra_superiorLayout.setHorizontalGroup(
            Barra_superiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Barra_superiorLayout.createSequentialGroup()
                .addComponent(Boton_cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 881, Short.MAX_VALUE))
        );
        Barra_superiorLayout.setVerticalGroup(
            Barra_superiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Barra_superiorLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Boton_cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo1.setBackground(new java.awt.Color(0, 0, 0));
        Titulo1.setFont(new java.awt.Font("Roboto Medium", 0, 36)); // NOI18N
        Titulo1.setForeground(new java.awt.Color(0, 0, 0));
        Titulo1.setText("DESTINOS NACIONALES");
        jPanel1.add(Titulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/DestinosImg.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 30, 350, 630));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 470, 10));

        Titulo_nombre1.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        Titulo_nombre1.setForeground(new java.awt.Color(0, 0, 0));
        Titulo_nombre1.setText("Seleccionar Destino:");
        jPanel1.add(Titulo_nombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 470, 10));

        Titulo_nombre2.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        Titulo_nombre2.setForeground(new java.awt.Color(0, 0, 0));
        Titulo_nombre2.setText("Fecha ida:");
        jPanel1.add(Titulo_nombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, -1));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 470, 10));

        Titulo_nombre3.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        Titulo_nombre3.setForeground(new java.awt.Color(0, 0, 0));
        Titulo_nombre3.setText("Fecha vuelta:");
        jPanel1.add(Titulo_nombre3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, -1, -1));

        Box_destinos.setBackground(new java.awt.Color(255, 255, 255));
        Box_destinos.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        Box_destinos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar Destino", "Tarapoto", "Puno", "Cusco", "Iquitos", "Tumbes", "Jequetepeque", "Ica", "Arequipa", "Jauja", "Trujillo", "Chiclayo", "Piura" }));
        Box_destinos.setToolTipText("");
        Box_destinos.setBorder(null);
        Box_destinos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(Box_destinos, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 300, 40));

        Boton.setBackground(new java.awt.Color(0, 22, 59));
        Boton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel3.setFont(new java.awt.Font("Roboto Slab ExtraBold", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Regresar");

        javax.swing.GroupLayout BotonLayout = new javax.swing.GroupLayout(Boton);
        Boton.setLayout(BotonLayout);
        BotonLayout.setHorizontalGroup(
            BotonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BotonLayout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(36, 36, 36))
        );
        BotonLayout.setVerticalGroup(
            BotonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BotonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jPanel1.add(Boton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 580, -1, -1));

        Boton1.setBackground(new java.awt.Color(0, 22, 59));
        Boton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel4.setFont(new java.awt.Font("Roboto Slab ExtraBold", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Continuar");

        javax.swing.GroupLayout Boton1Layout = new javax.swing.GroupLayout(Boton1);
        Boton1.setLayout(Boton1Layout);
        Boton1Layout.setHorizontalGroup(
            Boton1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Boton1Layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(36, 36, 36))
        );
        Boton1Layout.setVerticalGroup(
            Boton1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Boton1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jPanel1.add(Boton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 580, -1, -1));

        Barra_superior1.setBackground(new java.awt.Color(0, 22, 59));

        Boton_cerrar1.setBackground(new java.awt.Color(63, 31, 46));

        X_salir1.setBackground(new java.awt.Color(255, 255, 255));
        X_salir1.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        X_salir1.setForeground(new java.awt.Color(255, 255, 255));
        X_salir1.setText("  X");
        X_salir1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout Boton_cerrar1Layout = new javax.swing.GroupLayout(Boton_cerrar1);
        Boton_cerrar1.setLayout(Boton_cerrar1Layout);
        Boton_cerrar1Layout.setHorizontalGroup(
            Boton_cerrar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(X_salir1, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
        );
        Boton_cerrar1Layout.setVerticalGroup(
            Boton_cerrar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(X_salir1, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout Barra_superior1Layout = new javax.swing.GroupLayout(Barra_superior1);
        Barra_superior1.setLayout(Barra_superior1Layout);
        Barra_superior1Layout.setHorizontalGroup(
            Barra_superior1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Barra_superior1Layout.createSequentialGroup()
                .addComponent(Boton_cerrar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 881, Short.MAX_VALUE))
        );
        Barra_superior1Layout.setVerticalGroup(
            Barra_superior1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Barra_superior1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Boton_cerrar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(Barra_superior1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void X_salirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_X_salirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_X_salirMouseClicked

    private void X_salirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_X_salirMouseEntered
        Boton_cerrar.setBackground(Color.red);
        X_salir.setForeground(Color.white);
    }//GEN-LAST:event_X_salirMouseEntered

    private void X_salirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_X_salirMouseExited
        Boton_cerrar.setBackground(new Color(63,31,46));
        X_salir.setForeground(Color.white);
    }//GEN-LAST:event_X_salirMouseExited

    private void X_salirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_X_salirMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_X_salirMousePressed

    private void Barra_superiorMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Barra_superiorMouseDragged
        int x=evt.getXOnScreen();
        int y=evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_Barra_superiorMouseDragged

    private void Barra_superiorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Barra_superiorMousePressed
        xMouse=evt.getX();
        yMouse=evt.getY();
    }//GEN-LAST:event_Barra_superiorMousePressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Barra_superior;
    private javax.swing.JPanel Barra_superior1;
    private javax.swing.JPanel Boton;
    private javax.swing.JPanel Boton1;
    private javax.swing.JPanel Boton_cerrar;
    private javax.swing.JPanel Boton_cerrar1;
    private javax.swing.JComboBox<String> Box_destinos;
    private javax.swing.JLabel Titulo;
    private javax.swing.JLabel Titulo1;
    private javax.swing.JLabel Titulo_nombre1;
    private javax.swing.JLabel Titulo_nombre2;
    private javax.swing.JLabel Titulo_nombre3;
    private javax.swing.JLabel X_salir;
    private javax.swing.JLabel X_salir1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables
}