package com.g4.view;
  
import java.util.Date;

public class frmDestination extends javax.swing.JFrame {

    public frmDestination() {
        initComponents();
        Date currentDate = new Date();
        jDateChooser.setMinSelectableDate(currentDate);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Titulo1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        Titulo_nombre1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        Titulo_nombre2 = new javax.swing.JLabel();
        Box_destinos = new javax.swing.JComboBox<>();
        Boton = new javax.swing.JPanel();
        btnReturn = new javax.swing.JLabel();
        Boton1 = new javax.swing.JPanel();
        btnContinue = new javax.swing.JLabel();
        jDateChooser = new com.toedter.calendar.JDateChooser();
        Barra_superior2 = new javax.swing.JPanel();
        Boton_cerrar2 = new javax.swing.JPanel();
        X_salir2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo1.setBackground(new java.awt.Color(0, 0, 0));
        Titulo1.setFont(new java.awt.Font("Roboto Medium", 0, 36)); // NOI18N
        Titulo1.setForeground(new java.awt.Color(0, 0, 0));
        Titulo1.setText("DESTINOS NACIONALES");
        jPanel1.add(Titulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/g4/view/images/destinationImg.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 30, 350, 630));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 470, 10));

        Titulo_nombre1.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        Titulo_nombre1.setForeground(new java.awt.Color(0, 0, 0));
        Titulo_nombre1.setText("Seleccionar Destino:");
        jPanel1.add(Titulo_nombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 470, 10));

        Titulo_nombre2.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        Titulo_nombre2.setForeground(new java.awt.Color(0, 0, 0));
        Titulo_nombre2.setText("Fecha ida:");
        jPanel1.add(Titulo_nombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, -1, -1));

        Box_destinos.setBackground(new java.awt.Color(255, 255, 255));
        Box_destinos.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        Box_destinos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar Destino", "Arequipa", "Junin", "Puno", "Tacna", "Tarapoto" }));
        Box_destinos.setToolTipText("");
        Box_destinos.setBorder(null);
        Box_destinos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(Box_destinos, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 300, 40));

        Boton.setBackground(new java.awt.Color(0, 22, 59));
        Boton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnReturn.setFont(new java.awt.Font("Roboto Slab ExtraBold", 0, 18)); // NOI18N
        btnReturn.setForeground(new java.awt.Color(255, 255, 255));
        btnReturn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnReturn.setText("Regresar");

        javax.swing.GroupLayout BotonLayout = new javax.swing.GroupLayout(Boton);
        Boton.setLayout(BotonLayout);
        BotonLayout.setHorizontalGroup(
            BotonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnReturn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
        );
        BotonLayout.setVerticalGroup(
            BotonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnReturn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(Boton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 580, -1, -1));

        Boton1.setBackground(new java.awt.Color(0, 22, 59));
        Boton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnContinue.setFont(new java.awt.Font("Roboto Slab ExtraBold", 0, 18)); // NOI18N
        btnContinue.setForeground(new java.awt.Color(255, 255, 255));
        btnContinue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnContinue.setText("Continuar");

        javax.swing.GroupLayout Boton1Layout = new javax.swing.GroupLayout(Boton1);
        Boton1.setLayout(Boton1Layout);
        Boton1Layout.setHorizontalGroup(
            Boton1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnContinue, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );
        Boton1Layout.setVerticalGroup(
            Boton1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnContinue, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(Boton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 580, -1, -1));
        jPanel1.add(jDateChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 360, 300, -1));

        Barra_superior2.setBackground(new java.awt.Color(0, 22, 59));

        Boton_cerrar2.setBackground(new java.awt.Color(63, 31, 46));

        X_salir2.setBackground(new java.awt.Color(255, 255, 255));
        X_salir2.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        X_salir2.setForeground(new java.awt.Color(255, 255, 255));
        X_salir2.setText("  X");
        X_salir2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout Boton_cerrar2Layout = new javax.swing.GroupLayout(Boton_cerrar2);
        Boton_cerrar2.setLayout(Boton_cerrar2Layout);
        Boton_cerrar2Layout.setHorizontalGroup(
            Boton_cerrar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(X_salir2, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
        );
        Boton_cerrar2Layout.setVerticalGroup(
            Boton_cerrar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(X_salir2, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout Barra_superior2Layout = new javax.swing.GroupLayout(Barra_superior2);
        Barra_superior2.setLayout(Barra_superior2Layout);
        Barra_superior2Layout.setHorizontalGroup(
            Barra_superior2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Barra_superior2Layout.createSequentialGroup()
                .addComponent(Boton_cerrar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 881, Short.MAX_VALUE))
        );
        Barra_superior2Layout.setVerticalGroup(
            Barra_superior2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Barra_superior2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Boton_cerrar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(Barra_superior2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Barra_superior2;
    private javax.swing.JPanel Boton;
    private javax.swing.JPanel Boton1;
    private javax.swing.JPanel Boton_cerrar2;
    public javax.swing.JComboBox<String> Box_destinos;
    private javax.swing.JLabel Titulo1;
    private javax.swing.JLabel Titulo_nombre1;
    private javax.swing.JLabel Titulo_nombre2;
    private javax.swing.JLabel X_salir2;
    public javax.swing.JLabel btnContinue;
    public javax.swing.JLabel btnReturn;
    public com.toedter.calendar.JDateChooser jDateChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}