package com.g4.view;

public class frmRegister extends javax.swing.JFrame {

    int xMouse, yMouse;
    public frmRegister() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgPanel = new javax.swing.JPanel();
        iconImage = new javax.swing.JLabel();
        titlePanel = new javax.swing.JPanel();
        exitPanel = new javax.swing.JPanel();
        btnExit = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        lblDni = new javax.swing.JLabel();
        txtDni = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        lblPhone = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        lblDestination = new javax.swing.JLabel();
        boxDestination = new javax.swing.JComboBox<>();
        registerPanel = new javax.swing.JPanel();
        btnRegister = new javax.swing.JLabel();
        continuePanel = new javax.swing.JPanel();
        btnContinue = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        bgPanel.setBackground(new java.awt.Color(255, 255, 255));
        bgPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iconImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/g4/view/images/mujer_aeropuerto.jpg"))); // NOI18N
        bgPanel.add(iconImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 30, 320, 630));

        titlePanel.setBackground(new java.awt.Color(0, 22, 59));

        exitPanel.setBackground(new java.awt.Color(63, 31, 46));

        btnExit.setBackground(new java.awt.Color(255, 255, 255));
        btnExit.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnExit.setText("X");
        btnExit.setToolTipText("");
        btnExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout exitPanelLayout = new javax.swing.GroupLayout(exitPanel);
        exitPanel.setLayout(exitPanelLayout);
        exitPanelLayout.setHorizontalGroup(
            exitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(exitPanelLayout.createSequentialGroup()
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        exitPanelLayout.setVerticalGroup(
            exitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(exitPanelLayout.createSequentialGroup()
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout titlePanelLayout = new javax.swing.GroupLayout(titlePanel);
        titlePanel.setLayout(titlePanelLayout);
        titlePanelLayout.setHorizontalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlePanelLayout.createSequentialGroup()
                .addComponent(exitPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 881, Short.MAX_VALUE))
        );
        titlePanelLayout.setVerticalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, titlePanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(exitPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        bgPanel.add(titlePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 30));

        lblTitle.setBackground(new java.awt.Color(0, 0, 0));
        lblTitle.setFont(new java.awt.Font("Roboto Medium", 0, 36)); // NOI18N
        lblTitle.setText("REGISTRO");
        bgPanel.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        lblName.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        lblName.setText("Nombre Completo");
        bgPanel.add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 124, -1, -1));

        txtName.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        txtName.setForeground(new java.awt.Color(204, 204, 204));
        txtName.setText("Ingrese el nombre completo");
        txtName.setBorder(null);
        bgPanel.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 144, 420, 40));
        bgPanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 184, 420, 10));

        lblDni.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        lblDni.setText("DNI");
        bgPanel.add(lblDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 204, -1, -1));

        txtDni.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        txtDni.setForeground(new java.awt.Color(204, 204, 204));
        txtDni.setText("Ingrese el DNI");
        txtDni.setBorder(null);
        bgPanel.add(txtDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 236, 420, 40));
        bgPanel.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 276, 420, 10));

        lblPhone.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        lblPhone.setText("Teléfono");
        bgPanel.add(lblPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 296, -1, -1));

        txtPhone.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        txtPhone.setForeground(new java.awt.Color(204, 204, 204));
        txtPhone.setText("Ingrese el numero telefonico");
        txtPhone.setBorder(null);
        bgPanel.add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 328, 420, 40));
        bgPanel.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 368, 420, 10));

        lblEmail.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        lblEmail.setText("Correo eléctrónico");
        bgPanel.add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 398, -1, -1));

        txtEmail.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(204, 204, 204));
        txtEmail.setText("Ingrese el correo electronico");
        txtEmail.setBorder(null);
        bgPanel.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 418, 420, 40));
        bgPanel.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 458, 420, 10));

        lblDestination.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        lblDestination.setText("Destino");
        bgPanel.add(lblDestination, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 478, -1, -1));

        boxDestination.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        boxDestination.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar Destino", "Tarapoto", "Puno", "Cusco", "Iquitos", "Tumbes", "Jequetepeque", "Ica", "Arequipa", "Huancayo", "Trujillo", "Chiclayo", "Piura" }));
        boxDestination.setToolTipText("");
        boxDestination.setBorder(null);
        boxDestination.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bgPanel.add(boxDestination, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 510, 420, 40));

        registerPanel.setBackground(new java.awt.Color(0, 22, 59));
        registerPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnRegister.setFont(new java.awt.Font("Roboto Slab ExtraBold", 0, 18)); // NOI18N
        btnRegister.setForeground(new java.awt.Color(255, 255, 255));
        btnRegister.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnRegister.setText("Registrar");

        javax.swing.GroupLayout registerPanelLayout = new javax.swing.GroupLayout(registerPanel);
        registerPanel.setLayout(registerPanelLayout);
        registerPanelLayout.setHorizontalGroup(
            registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnRegister, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
        );
        registerPanelLayout.setVerticalGroup(
            registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnRegister, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        bgPanel.add(registerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 580, -1, -1));

        continuePanel.setBackground(new java.awt.Color(0, 22, 59));
        continuePanel.setPreferredSize(new java.awt.Dimension(143, 50));

        btnContinue.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        btnContinue.setForeground(new java.awt.Color(255, 255, 255));
        btnContinue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnContinue.setText("Continuar");

        javax.swing.GroupLayout continuePanelLayout = new javax.swing.GroupLayout(continuePanel);
        continuePanel.setLayout(continuePanelLayout);
        continuePanelLayout.setHorizontalGroup(
            continuePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnContinue, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
        );
        continuePanelLayout.setVerticalGroup(
            continuePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnContinue, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        bgPanel.add(continuePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 580, -1, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bgPanel;
    public javax.swing.JComboBox<String> boxDestination;
    public javax.swing.JLabel btnContinue;
    public javax.swing.JLabel btnExit;
    public javax.swing.JLabel btnRegister;
    private javax.swing.JPanel continuePanel;
    public javax.swing.JPanel exitPanel;
    private javax.swing.JLabel iconImage;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel lblDestination;
    private javax.swing.JLabel lblDni;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel registerPanel;
    public javax.swing.JPanel titlePanel;
    public javax.swing.JTextField txtDni;
    public javax.swing.JTextField txtEmail;
    public javax.swing.JTextField txtName;
    public javax.swing.JTextField txtPhone;
    // End of variables declaration//GEN-END:variables
}