package com.g4.view;

public class frmStart extends javax.swing.JFrame {

    /**
     * Creates new form frmStart
     */
    public frmStart() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgPanel = new javax.swing.JPanel();
        titlePanel = new javax.swing.JPanel();
        btnExit = new javax.swing.JLabel();
        startPanel = new javax.swing.JPanel();
        goToQueuePanel = new javax.swing.JPanel();
        btnGoToQueue = new javax.swing.JLabel();
        adminPanel = new javax.swing.JPanel();
        txtAdmin = new javax.swing.JLabel();
        lblAdmin = new javax.swing.JLabel();
        goToClientsPanel = new javax.swing.JPanel();
        btnGoToClients = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bgPanel.setBackground(new java.awt.Color(255, 255, 255));
        bgPanel.setPreferredSize(new java.awt.Dimension(902, 658));
        bgPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titlePanel.setBackground(new java.awt.Color(0, 0, 102));
        titlePanel.setPreferredSize(new java.awt.Dimension(902, 40));

        btnExit.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnExit.setText("X");

        javax.swing.GroupLayout titlePanelLayout = new javax.swing.GroupLayout(titlePanel);
        titlePanel.setLayout(titlePanelLayout);
        titlePanelLayout.setHorizontalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        titlePanelLayout.setVerticalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        bgPanel.add(titlePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, -1));

        startPanel.setBackground(new java.awt.Color(229, 213, 229));

        goToQueuePanel.setBackground(new java.awt.Color(102, 0, 102));
        goToQueuePanel.setForeground(new java.awt.Color(0, 153, 153));

        btnGoToQueue.setBackground(new java.awt.Color(255, 204, 255));
        btnGoToQueue.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        btnGoToQueue.setForeground(new java.awt.Color(236, 210, 250));
        btnGoToQueue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnGoToQueue.setText("V E R     C O L A");

        javax.swing.GroupLayout goToQueuePanelLayout = new javax.swing.GroupLayout(goToQueuePanel);
        goToQueuePanel.setLayout(goToQueuePanelLayout);
        goToQueuePanelLayout.setHorizontalGroup(
            goToQueuePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnGoToQueue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        goToQueuePanelLayout.setVerticalGroup(
            goToQueuePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnGoToQueue, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        adminPanel.setBackground(new java.awt.Color(255, 255, 255));

        txtAdmin.setText("Admin");

        javax.swing.GroupLayout adminPanelLayout = new javax.swing.GroupLayout(adminPanel);
        adminPanel.setLayout(adminPanelLayout);
        adminPanelLayout.setHorizontalGroup(
            adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, adminPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)
                .addContainerGap())
        );
        adminPanelLayout.setVerticalGroup(
            adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                .addContainerGap())
        );

        lblAdmin.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        lblAdmin.setForeground(new java.awt.Color(41, 29, 124));
        lblAdmin.setText("Administrador");

        goToClientsPanel.setBackground(new java.awt.Color(102, 0, 102));
        goToClientsPanel.setForeground(new java.awt.Color(255, 153, 255));

        btnGoToClients.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        btnGoToClients.setForeground(new java.awt.Color(255, 204, 255));
        btnGoToClients.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnGoToClients.setText("T I C K E T S");

        javax.swing.GroupLayout goToClientsPanelLayout = new javax.swing.GroupLayout(goToClientsPanel);
        goToClientsPanel.setLayout(goToClientsPanelLayout);
        goToClientsPanelLayout.setHorizontalGroup(
            goToClientsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnGoToClients, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
        );
        goToClientsPanelLayout.setVerticalGroup(
            goToClientsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnGoToClients, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout startPanelLayout = new javax.swing.GroupLayout(startPanel);
        startPanel.setLayout(startPanelLayout);
        startPanelLayout.setHorizontalGroup(
            startPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(startPanelLayout.createSequentialGroup()
                .addGroup(startPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(startPanelLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(adminPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(startPanelLayout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(startPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(goToQueuePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(goToClientsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(38, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, startPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblAdmin)
                .addGap(162, 162, 162))
        );
        startPanelLayout.setVerticalGroup(
            startPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(startPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lblAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(adminPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(goToQueuePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(goToClientsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        bgPanel.add(startPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 420, 360));

        getContentPane().add(bgPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel adminPanel;
    private javax.swing.JPanel bgPanel;
    public javax.swing.JLabel btnExit;
    public javax.swing.JLabel btnGoToClients;
    public javax.swing.JLabel btnGoToQueue;
    private javax.swing.JPanel goToClientsPanel;
    private javax.swing.JPanel goToQueuePanel;
    private javax.swing.JLabel lblAdmin;
    private javax.swing.JPanel startPanel;
    public javax.swing.JPanel titlePanel;
    public javax.swing.JLabel txtAdmin;
    // End of variables declaration//GEN-END:variables
}