package com.g4.view;

public class frmTicket extends javax.swing.JFrame {

    /**
     * Creates new form frmTicket
     */
    public frmTicket() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        originPanel1 = new javax.swing.JPanel();
        lblOrigin1 = new javax.swing.JLabel();
        backgroundPanel = new javax.swing.JPanel();
        panelTitlebar = new javax.swing.JPanel();
        btnClose = new javax.swing.JLabel();
        graphPanel = new javax.swing.JPanel();
        lblGraph = new javax.swing.JLabel();
        returnPanel = new javax.swing.JPanel();
        btnReturn = new javax.swing.JLabel();
        infoPanel = new javax.swing.JPanel();
        lblOriginTitle = new javax.swing.JLabel();
        lblPriceTitle = new javax.swing.JLabel();
        lblDestinationTitle = new javax.swing.JLabel();
        originPanel = new javax.swing.JPanel();
        lblOrigin = new javax.swing.JLabel();
        pricePanel = new javax.swing.JPanel();
        lblSolesSymbol = new javax.swing.JLabel();
        lblPriceSoles = new javax.swing.JLabel();
        lblRouteTitle = new javax.swing.JLabel();
        routePanel = new javax.swing.JPanel();
        lblRouteCalculated = new javax.swing.JLabel();
        destinationPanel = new javax.swing.JPanel();
        lblDestinationSelected = new javax.swing.JLabel();
        confirmPanel = new javax.swing.JPanel();
        btnConfirm = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();

        originPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblOrigin1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOrigin1.setText("Lima");

        javax.swing.GroupLayout originPanel1Layout = new javax.swing.GroupLayout(originPanel1);
        originPanel1.setLayout(originPanel1Layout);
        originPanel1Layout.setHorizontalGroup(
            originPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, originPanel1Layout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addComponent(lblOrigin1)
                .addGap(53, 53, 53))
        );
        originPanel1Layout.setVerticalGroup(
            originPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(originPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblOrigin1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backgroundPanel.setBackground(new java.awt.Color(255, 255, 255));
        backgroundPanel.setPreferredSize(new java.awt.Dimension(902, 658));
        backgroundPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelTitlebar.setBackground(new java.awt.Color(0, 0, 102));
        panelTitlebar.setPreferredSize(new java.awt.Dimension(902, 40));

        btnClose.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        btnClose.setForeground(new java.awt.Color(255, 255, 255));
        btnClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnClose.setText("X");

        javax.swing.GroupLayout panelTitlebarLayout = new javax.swing.GroupLayout(panelTitlebar);
        panelTitlebar.setLayout(panelTitlebarLayout);
        panelTitlebarLayout.setHorizontalGroup(
            panelTitlebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTitlebarLayout.createSequentialGroup()
                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(866, 866, 866))
        );
        panelTitlebarLayout.setVerticalGroup(
            panelTitlebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTitlebarLayout.createSequentialGroup()
                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        backgroundPanel.add(panelTitlebar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        graphPanel.setBackground(new java.awt.Color(242, 250, 250));

        lblGraph.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/g4/view/images/graphImg.png"))); // NOI18N

        javax.swing.GroupLayout graphPanelLayout = new javax.swing.GroupLayout(graphPanel);
        graphPanel.setLayout(graphPanelLayout);
        graphPanelLayout.setHorizontalGroup(
            graphPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(graphPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblGraph)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        graphPanelLayout.setVerticalGroup(
            graphPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(graphPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblGraph, javax.swing.GroupLayout.PREFERRED_SIZE, 567, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        backgroundPanel.add(graphPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 440, 620));

        returnPanel.setBackground(new java.awt.Color(153, 186, 186));
        returnPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnReturn.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        btnReturn.setForeground(new java.awt.Color(255, 255, 255));
        btnReturn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnReturn.setText("REGRESAR");

        javax.swing.GroupLayout returnPanelLayout = new javax.swing.GroupLayout(returnPanel);
        returnPanel.setLayout(returnPanelLayout);
        returnPanelLayout.setHorizontalGroup(
            returnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnReturn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        returnPanelLayout.setVerticalGroup(
            returnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnReturn, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        backgroundPanel.add(returnPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 570, -1, -1));

        infoPanel.setBackground(new java.awt.Color(249, 237, 243));

        lblOriginTitle.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        lblOriginTitle.setForeground(new java.awt.Color(41, 29, 124));
        lblOriginTitle.setText("Origen");

        lblPriceTitle.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        lblPriceTitle.setForeground(new java.awt.Color(41, 29, 124));
        lblPriceTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPriceTitle.setText("Precio del boleto");

        lblDestinationTitle.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        lblDestinationTitle.setForeground(new java.awt.Color(41, 29, 124));
        lblDestinationTitle.setText("Destino");

        originPanel.setBackground(new java.awt.Color(255, 255, 255));

        lblOrigin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOrigin.setText("Lima");

        javax.swing.GroupLayout originPanelLayout = new javax.swing.GroupLayout(originPanel);
        originPanel.setLayout(originPanelLayout);
        originPanelLayout.setHorizontalGroup(
            originPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(originPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblOrigin, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                .addContainerGap())
        );
        originPanelLayout.setVerticalGroup(
            originPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(originPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblOrigin)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pricePanel.setBackground(new java.awt.Color(255, 255, 255));

        lblSolesSymbol.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        lblSolesSymbol.setForeground(new java.awt.Color(70, 70, 70));
        lblSolesSymbol.setText("S/");

        lblPriceSoles.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblPriceSoles.setText("100");

        javax.swing.GroupLayout pricePanelLayout = new javax.swing.GroupLayout(pricePanel);
        pricePanel.setLayout(pricePanelLayout);
        pricePanelLayout.setHorizontalGroup(
            pricePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pricePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSolesSymbol, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPriceSoles, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                .addContainerGap())
        );
        pricePanelLayout.setVerticalGroup(
            pricePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pricePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lblSolesSymbol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblPriceSoles, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        lblRouteTitle.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        lblRouteTitle.setForeground(new java.awt.Color(41, 29, 124));
        lblRouteTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRouteTitle.setText("Ruta");

        routePanel.setBackground(new java.awt.Color(255, 255, 255));

        lblRouteCalculated.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRouteCalculated.setText("Ruta");

        javax.swing.GroupLayout routePanelLayout = new javax.swing.GroupLayout(routePanel);
        routePanel.setLayout(routePanelLayout);
        routePanelLayout.setHorizontalGroup(
            routePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(routePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblRouteCalculated, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
                .addContainerGap())
        );
        routePanelLayout.setVerticalGroup(
            routePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(routePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblRouteCalculated, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        destinationPanel.setBackground(new java.awt.Color(255, 255, 255));

        lblDestinationSelected.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDestinationSelected.setText("Destino");

        javax.swing.GroupLayout destinationPanelLayout = new javax.swing.GroupLayout(destinationPanel);
        destinationPanel.setLayout(destinationPanelLayout);
        destinationPanelLayout.setHorizontalGroup(
            destinationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(destinationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDestinationSelected, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                .addContainerGap())
        );
        destinationPanelLayout.setVerticalGroup(
            destinationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(destinationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDestinationSelected)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout infoPanelLayout = new javax.swing.GroupLayout(infoPanel);
        infoPanel.setLayout(infoPanelLayout);
        infoPanelLayout.setHorizontalGroup(
            infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoPanelLayout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(lblOriginTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblDestinationTitle)
                .addGap(100, 100, 100))
            .addGroup(infoPanelLayout.createSequentialGroup()
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(infoPanelLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(routePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(infoPanelLayout.createSequentialGroup()
                                .addComponent(originPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54)
                                .addComponent(destinationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblRouteTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(infoPanelLayout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pricePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblPriceTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        infoPanelLayout.setVerticalGroup(
            infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, infoPanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(infoPanelLayout.createSequentialGroup()
                        .addComponent(lblOriginTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(originPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(infoPanelLayout.createSequentialGroup()
                        .addComponent(lblDestinationTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(destinationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(lblRouteTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(routePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(lblPriceTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pricePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        backgroundPanel.add(infoPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 150, 420, 380));

        confirmPanel.setBackground(new java.awt.Color(0, 153, 153));
        confirmPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnConfirm.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        btnConfirm.setForeground(new java.awt.Color(255, 255, 255));
        btnConfirm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnConfirm.setText("CONFIRMAR");

        javax.swing.GroupLayout confirmPanelLayout = new javax.swing.GroupLayout(confirmPanel);
        confirmPanel.setLayout(confirmPanelLayout);
        confirmPanelLayout.setHorizontalGroup(
            confirmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnConfirm, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
        );
        confirmPanelLayout.setVerticalGroup(
            confirmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnConfirm, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        backgroundPanel.add(confirmPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 570, -1, -1));

        lblTitle.setFont(new java.awt.Font("Roboto Black", 0, 36)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(41, 29, 124));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("TRAYECTO");
        backgroundPanel.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 80, 350, -1));

        getContentPane().add(backgroundPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backgroundPanel;
    public javax.swing.JLabel btnClose;
    public javax.swing.JLabel btnConfirm;
    public javax.swing.JLabel btnReturn;
    private javax.swing.JPanel confirmPanel;
    private javax.swing.JPanel destinationPanel;
    private javax.swing.JPanel graphPanel;
    private javax.swing.JPanel infoPanel;
    public javax.swing.JLabel lblDestinationSelected;
    private javax.swing.JLabel lblDestinationTitle;
    private javax.swing.JLabel lblGraph;
    private javax.swing.JLabel lblOrigin;
    private javax.swing.JLabel lblOrigin1;
    private javax.swing.JLabel lblOriginTitle;
    public javax.swing.JLabel lblPriceSoles;
    private javax.swing.JLabel lblPriceTitle;
    public javax.swing.JLabel lblRouteCalculated;
    private javax.swing.JLabel lblRouteTitle;
    private javax.swing.JLabel lblSolesSymbol;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel originPanel;
    private javax.swing.JPanel originPanel1;
    public javax.swing.JPanel panelTitlebar;
    private javax.swing.JPanel pricePanel;
    private javax.swing.JPanel returnPanel;
    private javax.swing.JPanel routePanel;
    // End of variables declaration//GEN-END:variables
}